### ISSUE TITLE
OBI terms needed for HuBMAP (Kevin and Alex group)

### ISSUE THREAD

**Issue by nsuvarnaiari** [nih-cfde/ontologyWG#2]
@ropelews and @khanshawPSC from HuBMAP requested new OBI terms. Attaching a file with the list.

Kevin/Alex, could you please send us any documentation/publications/web page links that can help us understand what each of these terms are so that we can put together definitions before submitting to OBI? It will be very helpful if you could send them sometime this month.

The plan is to submit the terms to OBI to get provisional ids so that you can start using them in preparation for the next CFDE portal release in August. Soon after we get the provisional ids, we will start working on putting together all the annotations and relationships for these terms that will be needed to create them in OBI. 

Thanks,
Suvvi

[HubmapAssayCFDE_Through_Q3_2021.docx](https://github.com/nih-cfde/ontologyWG/files/6695483/HubmapAssayCFDE_Through_Q3_2021.docx)

**Comment by khanshawPSC** [comment]
Hello, Suvvi.

We will collect this info and get it back to you.

**Comment by mgiglio99** [comment]
Hello Kevin and Alex,

Here is as link to our draft of term requests for OBI based on the list you sent us.
https://docs.google.com/spreadsheets/d/1onkUr1CRHZGktGFYn7JuH_5PFHV5Tm1kz1LT38FN1p0/edit?usp=sharing

In particular, please review our definitions of the terms to see if they are consistent with your usage.
In addition, there are few boxes highlighted in light yellow, these contain questions or clarifications of note.
Green rows indicate terms that already exist in OBI and therefore no action is needed for them. 
The term rows are in the same order as what you sent us in the Word doc.
We are planning to register OBI ids for these early next week. That will not prevent us tweaking definitions or parentage if needed.

Please let us know any questions or comments that you have,
Michelle and Suvvi

**Comment by khanshawPSC** [comment]
Alex and Ivan,

See the link for questions about our terms being working on by the CFDE.

https://docs.google.com/spreadsheets/d/1onkUr1CRHZGktGFYn7JuH_5PFHV5Tm1kz1LT38FN1p0/edit?usp=sharing

Thanks.

**Comment by mgiglio99** [comment]
Hi again @khanshawPSC and @ropelews ,

I now have OBI ids for the new proposed terms. I've added them to the google sheet above as well as added a new sheet to the doc that has just ids and term names for easy look up.
You can now use these for data submissions to the portal.

We look forward to chatting with you to make sure the definitions and parentage of the terms looks good.
Regards,
Michelle

**Comment by khanshawPSC** [comment]
Thank you so much, Michelle!
Appreciate your work on this. Alex is reviewing your questions and comment in the spreadsheet.

**Comment by nsuvarnaiari** [comment]
Hi @khanshawPSC  and @ropelews 

We are ready to submit the final template with OBI terms and definitions (with all the changes discussed in the slack) to OBI.
Please refer to this google doc with the terms and latest changes -
https://docs.google.com/spreadsheets/d/1_XaxKYQKO0nnH8yY8zwz_lhkweuUsO0ARyF22PI1uTk/edit?usp=sharing

The ids that are in this doc are the ones we registered for you before - so the ids will stay the same when the terms officially enter OBI.

Thanks,
Michelle and Suvvi

**Comment by khanshawPSC** [comment]
Thank you both for the work you have done on this.

**Comment by mgiglio99** [comment]
This work is complete. The above terms have been officially in OBI for a long time now - forgot to close this issue - closing...
