### ISSUE TITLE
OBI term for Metabolomics (Mano Maurya's group)

### ISSUE THREAD

**Issue by nsuvarnaiari** [nih-cfde/ontologyWG#3]
From Mano @mano-at-sdsc:

 For the upcoming submission, for assay_type, e.g., for GC-MS, are we using terms like OBI:0000470" or we can now use "OBO:CHMO_0000497". The page https://docs.nih-cfde.org/en/latest/c2m2/draft-C2M2_specification/#c2m2-technical-specification

Thanks,
Suvvi

**Comment by nsuvarnaiari** [comment]
Hi @mano-at-sdsc 

Michelle reserved an OBI id for "gas chromatography- mass spectrometry assay" after discussing with OBI folks. You can start using the id for CFDE portal submissions. It's not in the ontology yet but should be available in the next OBI release.

OBI:0003110 | gas chromatography mass spectrometry assay

Thanks,
Suvvi

**Comment by mano-at-sdsc** [comment]
Hi @nsuvarnaiari:

Thanks. Will use this for GC-MS. Other assay_type for which we will need OBI ID at finer level, for which currently I am just using OBI:0000470, are:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
</head>

<body link="#0563C1" vlink="#954F72">

assay_type | OBI_code | OBI_code_finer | URL_for_finer
-- | -- | -- | --
LC-MS | OBI:0000470 | OBO:CHMO_0000524 | http://purl.obolibrary.org/obo/CHMO_0000524
MALDI | OBI:0000470 | OBO:CHMO_0000519 | http://purl.obolibrary.org/obo/CHMO_0000519
API-MS | OBI:0000470 | OBO:MS_1000240 | http://purl.obolibrary.org/obo/MS_1000240
APCI-MS | OBI:0000470 | OBO:CHMO_0000473 | http://purl.obolibrary.org/obo/CHMO_0000473
ESI | OBI:0000470 | OBO:MS_1000073 | http://purl.obolibrary.org/obo/MS_1000073
IR MS | OBI:0000470 | OBO:CHMO_0000497 | http://purl.obolibrary.org/obo/CHMO_0000497



</body>

</html>

In case there are already OBI code for some of these and I may have missed them, please let me know.

Mano @mano-at-sdsc

**Comment by nsuvarnaiari** [comment]
Hi @mano-at-sdsc 

Thanks for sharing the list of terms for which you need OBI ids.
We will try to register ids for these terms with OBI soon so that you can start using them.

Please take a look at the actual names of the assay_type acronyms from your list and let us know if they are incorrect for the ones I was able to find a name. For the ones with a question mark, please tell us the name of the assay. We would really appreciate if you provide us definitions for these assays or a pubmed paper / some documentation / links that can help us define the terms.

LC-MS : liquid chromatography mass spectrometry 
MALDI : matrix-assisted laser desorption ionization time-of-flight mass-spectrometry or an other variant of MALDI?
API-MS : atmospheric pressure ionization mass spectrometry
APCI-MS : atmospheric pressure chemical ionization mass spectrometry
ESI : electrospray ionization mass spectrometry
IR MS : ?

Thanks,
Suvvi

**Comment by mano-at-sdsc** [comment]
Hi @nsuvarnaiari ,

Thanks, and sorry about the delay in response; sorry to make you search for these terms. We have decided to only use the terms "MS", "NMR", GC-MS" and "LC-MS". These already cover > 90% of the studies. For all others, we will use "MS". So, we request a OBI ID only for "LC-MS": liquid chromatography mass spectrometry. We already have one for MS, NMR and GC-MS.

Thanks.
Mano

**Comment by nsuvarnaiari** [comment]
Hi Mano,

We have registered an OBI id for "liquid chromatography mass spectrometry assay" for HuBMAP . You can start using this id in your metadata files.

Thanks,
Suvvi

**Comment by mano-at-sdsc** [comment]
Thanks, Suvvi.

Please share the OBI ID for "liquid chromatography mass spectrometry", or let me know if it is listed in one of the resource files here: https://github.com/hubmapconsortium/hubmap-ontology/tree/master/source_ontologies
or elsewhere.

Mano

**Comment by nsuvarnaiari** [comment]
Oh sorry @mano-at-sdsc, forgot to paste OBI id for "liquid chromatography mass spectrometry assay". It's OBI:0003097.

Thanks,
Suvvi

**Comment by mano-at-sdsc** [comment]
Thanks, @nsuvarnaiari . No worries.

Mano

**Comment by mgiglio99** [comment]
This work was finished a while ago - term has been live in OBI for a long time. Closing....
