### ISSUE TITLE
new OBI terms for 4DN

### ISSUE THREAD

**Issue by mgiglio99** [nih-cfde/ontologyWG#5]
(See email threads with Sarah Reiff - some are pasted below)

Hi Michelle and Suvvi,
 
I’ve edited the google sheets on 4DN ontology terms according to what we discussed last week. One thing we had discussed had been the ligation-free chromosome conformation sequencing term, and whether we should have a term as a parent that has both nuclear ligation and ligation-free chromosome conformation sequencing under it. I discussed this with the team, but we haven’t come to a consensus on what the term should be called or which specific assays should fall under the overall header (e.g. direct contact vs proximity, etc). I don’t want to add it to the ontology if there isn’t a clear consensus so I think we might not want to go down that route for now. It might be best to create those terms under DNA sequencing assay instead and we can add terms later and reorganize things if we decide on a clear path forward.
 
I’ll post the links again:
https://docs.google.com/spreadsheets/d/1ET2wTGBnin0GsPB1WtOuOk8NIeqv5hbe65Ew7Ud06xM/edit?usp=sharing
https://docs.google.com/document/d/1MGNIFxtgu3lw0-76qIyU_rvQApstUgmYwwSfReX5i4Y/edit?usp=sharing
 
Thanks for all your help with this!
 
Sarah

----------------------------
Hi Michelle,
 
I took a look at your comments. I’m happy to format the definitions the same way so I’m fine with that. As far as cool vs cooler, I know that .cool is the file extension and cooler is the software package, but I’m a little confused on which is the official name of the file format. Let me reach out to the developer and see if I can get a quick response.
 
Thanks,
Sarah
 
---------------

Hi Michelle,
 
We decided it might be worth adding mcool and scool as additional ontology terms for EDAM. I’ve updated the spreadsheet: [https://docs.google.com/spreadsheets/d/1ET2wTGBnin0GsPB1WtOuOk8NIeqv5hbe65Ew7Ud06xM/edit#gid=569144844](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1ET2wTGBnin0GsPB1WtOuOk8NIeqv5hbe65Ew7Ud06xM%2Fedit%23gid%3D569144844&data=04%7C01%7Cmgiglio%40som.umaryland.edu%7C36f037b22b4c471bdbdf08d9e74d5cbc%7C717009a620de461a88940312a395cac9%7C0%7C0%7C637795142327720006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9tD%2Fpe7O9HBO6gXAzThO1%2F%2BhPU9qXDAlL%2BPUJ2nuq9I%3D&reserved=0)
 
For the parent format I’m keeping the term name as “cooler”, as it seems more in line with the developer’s wishes. You mentioned that EDAM usually uses the file extension as the name, but bigwig and bigbed are a couple exceptions so hopefully it should be ok. Additionally, I used the same documentation and specification links for mcool and scool as for cooler, but scool does not have the same publication linked. This is because the publication references cool and mcool, but scool was developed later.
 
Let me know if you have any further comments.
 
Thanks,
Sarah

**Comment by mgiglio99** [comment]
making issues to track the NTRs
@nsuvarnaiari

**Comment by nsuvarnaiari** [comment]
Michelle and I have looked at all the details for the new OBI assay terms that you requested, and we made edits (minor) in some of the definitions, expanded the acronyms in the term labels and added “detection technique” for 3 terms.
We did not have edit permissions for “OBI” sheet in the [original google doc](https://docs.google.com/spreadsheets/d/1ET2wTGBnin0GsPB1WtOuOk8NIeqv5hbe65Ew7Ud06xM/edit#gid=569144844) that you sent us, so we made [another one](https://docs.google.com/spreadsheets/d/1_acp5LN7nulqfVhok3rilGlmj2ABN7788ZazPBpMxpA/edit?usp=sharing) where you can see the edits. Please take a look and let us know if something needs to be changed. Meanwhile I will be making an OBI assay template for these terms which will be submitted to OBI people to include in their ontology.
 
Regarding EDAM terms,  we are still waiting for Jeff from SPARC to test the terms in Interlex which will make CFDE specific terms for you to use until EDAM can add in their ontology. Will update you as soon as we hear from Jeff.
 
Final draft of OBI terms (just in case hyperlink above does not work):
https://docs.google.com/spreadsheets/d/1_acp5LN7nulqfVhok3rilGlmj2ABN7788ZazPBpMxpA/edit?usp=sharing
 
Thanks,
Suvvi

**Comment by nsuvarnaiari** [comment]
An [OBI template](https://docs.google.com/spreadsheets/d/14BKsTNcXiYXdLRvhqGoAnzbGY7hTROgtqfHUISRoz1Q/edit?usp=sharing) for these terms was shared with OBI group for review in OBI-devel call on 04/22/2022. This template has minor edits in "definition_source" field when compared to the google doc posted in the previous comment.

We will initiate a PR after OBI group reviews it.

**Comment by mgiglio99** [comment]
These terms are now live in OBI.
