### ISSUE TITLE
NTR: capillary electrophoresis mass spectrometry

### ISSUE THREAD

**Issue by mgiglio99** [nih-cfde/ontologyWG#8]
Hello Michelle, 
my name is Jackie and I work at the Pittsburgh Supercomputing Center (PSC) as a Data Curator and Metadata Librarian.  Alex Ropelewski at PSC referred me to you regarding a question about OBI terms. We currently have an assay type CE-MS, [Capillary electrophoresis–mass spectrometry](https://en.wikipedia.org/wiki/Capillary_electrophoresis%E2%80%93mass_spectrometry), that is not listed in [OBI](https://ontobee.org/search?ontology=OBI&keywords=Capillary+electrophoresis+Mass+Spectrometry&submit=Search+terms). Would you be the correct person to contact to have that added to OBI? We reference it as part of our CFDE submission. I appreciate any guidance you can share. Thank you!

**Comment by mgiglio99** [comment]
@j-uranic
Apologies I didn't tag you on this sooner.
And apologies we haven't had a chance yet to get this term for you. A lot of deadlines happening lately - but I plan to get to this soon.

**Comment by j-uranic** [comment]
Hi @mgiglio99 , thanks for the letting me know.

**Comment by j-uranic** [comment]
Hi @mgiglio99, we have another CFDE submission deadline on December 15th. Would this term be available to use then?

**Comment by nsuvarnaiari** [comment]
Hi @j-uranic,

We can provide you a provisional OBI id for this term that you can use in your submission. Please review the term metadata below and suggest any edits.

Term: capillary electrophoresis-mass spectrometry assay
Parent: mass spectrometry assay (OBI:0000470)
Definition: A mass spectrometry assay where charged metabolites are separated based on the movement of ions under electrophoretic and/or electro-osmotic forces produced by the application of an electric field with a mass spectrometer.
Dbxrefs: https://link.springer.com/protocol/10.1007/978-1-4939-2377-9_9         
https://www.sciencedirect.com/science/article/abs/pii/B9780128122938000050              
Exact synonym: CE-MS

Thanks,
Suvvi

**Comment by j-uranic** [comment]
Hello @nsuvarnaiari and @mgiglio99,
 
While I was looking for a dataset to compare against the term metadata for the provisional OBI you provided, I realized the CE-MS schema had been deprecated in our repository - which is why an OBI term for it had not been set up for our CFDE submission, and my request to have one created was in error. 

I sincerely apologize for the misunderstanding on my part and I hope this was not too much of an inconvenience. I truly appreciate your assistance and thank you for your help. 

Many thanks,
Jackie

**Comment by mgiglio99** [comment]
Hi Jackie,
No worries, it's no problem at all.
We'll go ahead and close this issue since you no longer need the term.
Best,
Michelle
